spring:
  application:
    name: eureka-server #应用名,同一实例下的集群要相同
server:
  port: 8762
eureka:
  instance:
    hostname: eureka02
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.3.108:8761/eureka/ #对外暴露的注册地址,需要注册到另外的一个8761地址,构建群集环境