spring:
  application:
    name: order-service #应用名,同一实例下的集群要相同
server:
  port: 9090
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: #下行是注册到服务注册中心
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#开启对 Feign 对 hystrix 的支持
feign:
  hystrix:
    enabled: true
  client:
    config:
      defalut:
        connection-timeout: 5000 #指定Feign连接提供者的超时时限
        readTimeout: 5000 #指定Feign从请求到获取提供者响应的超时时限